name: cod-classifier

services:
  cod-classifier:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cod-classifier
    ports:
      # FastAPI Ports
      - "${FASTAPI_PORT}:8000"
      # MLflow UI Port
      - "${MLFLOW_UI_PORT}:5000"
    volumes:
      - .:/app # To support hot reloading
    env_file:
      - .env
    restart: always
    networks:
      - cod-classifier-network

networks:
  cod-classifier-network:
    driver: bridge
